In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [3]:
read_file = pd.read_excel ("trombosit.xlsx")

In [6]:
read_file.to_csv ("trombosit.csv",  
                  index = None, 
                  header=True) 

In [7]:
df = pd.DataFrame(pd.read_csv("trombosit.csv"))

In [8]:
df

pc   pdw   mpv  pct  stage
0    1075  12.9  12.6  0.7      4
1     950  11.9  10.9  0.6      4
2     890  11.2  10.8  0.5      4
3     874  10.9  10.7  0.5      4
4     859  10.8  10.9  0.5      4
..    ...   ...   ...  ...    ...
364   178   6.4   6.5  0.0      1
365   177   6.3   6.5  0.0      1
366   160   6.2   6.3  0.0      1
367   159   6.3   6.5  0.0      1
368   152   6.2   6.2  0.0      1

[369 rows x 5 columns]

In [9]:
platelet_dataset = pd.read_csv('trombosit.csv')

In [10]:
X = platelet_dataset.drop(columns='stage', axis=1)
Y = platelet_dataset['stage']

In [11]:
scaler = StandardScaler()

In [12]:
scaler.fit(X)

StandardScaler()

In [13]:
standardized_data = scaler.transform(X)

In [14]:
print(standardized_data)

[[ 3.75325803  3.25805852  3.16372248  3.00144098]
 [ 3.00172985  2.42201986  1.69592933  2.4209432 ]
 [ 2.64099632  1.8367928   1.60958856  1.84044542]
 ...
 [-1.74792829 -2.34340051 -2.27574623 -1.06204351]
 [-1.75394051 -2.25979664 -2.10306469 -1.06204351]
 [-1.79602609 -2.34340051 -2.36208701 -1.06204351]]


In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, stratify=Y, random_state=2)

In [16]:
classifier = svm.SVC(kernel='linear')

In [17]:
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [18]:
X_train_prediction = classifier.predict(X_train)

In [19]:
X_test_prediction = classifier.predict(X_test)

In [20]:
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [21]:
print(training_data_accuracy)

0.7906976744186046


In [22]:
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print(test_data_accuracy)

0.8918918918918919


In [23]:
import pickle
filename="trombositmodel.sav"
pickle.dump(classifier, open(filename,'wb'))

In [24]:
loaded_model=pickle.load(open("trombositmodel.sav",'rb'))